### ISSUE TITLE
mask external provider data

### ISSUE THREAD

**Issue by stempher** [farzadmf/termask#10]
Hi
I use an external provider and in the data block I can’t mask the token
```
data "external" "sa" {
  program = ["sh", "${path.module}/get_permission.sh"]
  query   = {
    token     = var.token
    url       = var.url
  }
}
```

Run:
```
terraform plan -no-color | termask -m tf -p token
```

Plan is not mask:
```
 <= data "external" "sa"  {
       + id      = (known after apply)
       + program = [
           + "sh",
           + "modules/k8s/get_permission.sh",
         ]
       + query   = {
           + "token"     = "eyJhbGci...."
           + "url"       = "https://..."
         }
       + result  = (known after apply)
     }
```

**Comment by farzadmf** [comment]
Hi @stempher and thank you for reporting this issue. The only reason I can think of is the characters being used as the `token` value.

At the moment, I use this regex `[a-zA-Z0-9%;=/._-]` to match the characters used for value, and I'm assuming that the `token` in your scenario has characters not present in this character class.

**Comment by stempher** [comment]
This is a service account token from kubernetes. It uses symbols `[a-zA-Z0-9._-]`, length string - 850 symbols

**Comment by farzadmf** [comment]
Is it the base64 encoded one or the decoded one? Are you sure it doesn't contain any newline character or something?

I did two tests:
- One from a token from my cluster, and it seems to be working
- I copy/pasted your code snippet and replaced the value in `+ "token"     = "eyJhbGci...."` (`eyJhbGci....`) with my actual base64 decoded token, and it seems to be working as well:
```bash
cat test_file | tf -m tf -p token
```
and the output:
```
 <= data "external" "sa"  {
       + id      = (known after apply)
       + program = [
           + "sh",
           + "modules/k8s/get_permission.sh",
         ]
       + query   = {
           + "token"     = "***"
           + "url"       = "https://..."
         }
       + result  = (known after apply)
     }
```

**Comment by stempher** [comment]
I'm sorry. True, the token contained a newline character. It works right

**Comment by farzadmf** [comment]
Great :slightly_smiling_face: good to know. So I'm gonna close this issue. Feel free to re-open
