### ISSUE TITLE
unable to build app

### ISSUE THREAD

**Issue by m0ps** [farzadmf/termask#11]
The last commit https://github.com/farzadmf/termask/commit/3111269e9dd5ac6e2648e6111f0659efda82c8a2 broke the build process. git repo on azure can't be found (or read all permission is not granted).

**Comment by farzadmf** [comment]
OMG, I'm so sorry! I didn't mean to push that 😝; I'll fix it ASAP

And thank you for pointing that out

**Comment by farzadmf** [comment]
@m0ps should be fixed now; please let me know if there's any problem
