### ISSUE TITLE
Some properties aren't masked

### ISSUE THREAD

**Issue by bootswithdefer** [farzadmf/termask#13]
Some properties aren't masked, while others are.  Examples are from aws_db_option_group.  Seems to be related to commas "," and hash "#" characters.

`terraform plan -no-color | termask -m tf -p value -i -l`

```
          - option_settings {
              - name  = "SQLNET.CRYPTO_CHECKSUM_SERVER" -> null
              - value = "***" -> null
            }
          - option_settings {
              - name  = "SQLNET.CRYPTO_CHECKSUM_TYPES_SERVER" -> null
              - value = "SHA256,SHA1" -> null
            }
          - option_settings {
              - name  = "SQLNET.ENCRYPTION_SERVER" -> null
              - value = "***" -> null
            }
          - option_settings {
              - name  = "SQLNET.ENCRYPTION_TYPES_SERVER" -> null
              - value = "***" -> null
            }
```

Also it doesn't mask this removed password:
```
          - option_settings {
              - name  = "AGENT_REGISTRATION_PASSWORD" -> null
              - value = "my#exposed#password" -> null
            }
```

**Comment by farzadmf** [comment]
The reason is that there are some characters that are not recognized by the pattern I'm using.

@bootswithdefer can you tell me what are the valid characters in the removed password you're trying to mask?

**Comment by farzadmf** [comment]
Comma and hash sign now should be recognized; feel free to re-open if the issue's still there
